//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitComponentVersion.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitComponentVersion.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another?.
        /// </summary>
        internal static string ADD_ANOTHER {
            get {
                return ResourceManager.GetString("ADD_ANOTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are your components so far..
        /// </summary>
        internal static string COMPONENTS_SO_FAR {
            get {
                return ResourceManager.GetString("COMPONENTS_SO_FAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Those are all the directories that look like components..
        /// </summary>
        internal static string DONE_WITH_SUGGESTED_DIRECTORIES {
            get {
                return ResourceManager.GetString("DONE_WITH_SUGGESTED_DIRECTORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of a component.
        /// </summary>
        internal static string ENTER_COMPONENT_NAME {
            get {
                return ResourceManager.GetString("ENTER_COMPONENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Component!.
        /// </summary>
        internal static string INVALID_COMPONENT {
            get {
                return ResourceManager.GetString("INVALID_COMPONENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s add some components.
        /// </summary>
        internal static string LETS_ADD_COMPONENTS {
            get {
                return ResourceManager.GetString("LETS_ADD_COMPONENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, Good Bye!.
        /// </summary>
        internal static string OK_GOOD_BYE {
            get {
                return ResourceManager.GetString("OK_GOOD_BYE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok. Now let&apos;s assign your folders to a component..
        /// </summary>
        internal static string OK_NOW_ASSIGN_FOLDERS_TO_COMPONENTS {
            get {
                return ResourceManager.GetString("OK_NOW_ASSIGN_FOLDERS_TO_COMPONENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &lt;ENTER&gt; without any input to finish.
        /// </summary>
        internal static string PRESS_ENTER_TO_FINISH {
            get {
                return ResourceManager.GetString("PRESS_ENTER_TO_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Arguments.
        /// </summary>
        internal static string RET_INVALID_ARGS {
            get {
                return ResourceManager.GetString("RET_INVALID_ARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Command.
        /// </summary>
        internal static string RET_INVALID_COMMAND {
            get {
                return ResourceManager.GetString("RET_INVALID_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string RET_SUCCESS {
            get {
                return ResourceManager.GetString("RET_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string RET_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("RET_UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the pre-release tag for this component?.
        /// </summary>
        internal static string WHAT_IS_THE_COMPONENT_PRE_RELEASE_TAG {
            get {
                return ResourceManager.GetString("WHAT_IS_THE_COMPONENT_PRE_RELEASE_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the next version of this component?.
        /// </summary>
        internal static string WHAT_IS_THE_COMPONENT_VERSION {
            get {
                return ResourceManager.GetString("WHAT_IS_THE_COMPONENT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add more now if you would like..
        /// </summary>
        internal static string YOU_CAN_ADD_MORE {
            get {
                return ResourceManager.GetString("YOU_CAN_ADD_MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes have been written to {0}.
        /// </summary>
        internal static string YOUR_CHANGES_WERE_WRITTEN_TO {
            get {
                return ResourceManager.GetString("YOUR_CHANGES_WERE_WRITTEN_TO", resourceCulture);
            }
        }
    }
}
